# docker-compose.yml
services:
  postgres:
    image: postgres:17
    environment:
      - POSTGRES_DB=ledger
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - ./.volumes/postgres/data:/var/lib/postgresql/data

